"""add available to stock_new

Revision ID: 18a31b795743
Revises: 19e55b71890a
Create Date: 2016-04-06 22:08:23.241391

"""

# revision identifiers, used by Alembic.
revision = '18a31b795743'
down_revision = '19e55b71890a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_new', sa.Column('available', sa.Boolean(), default=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_new', 'available')
    ### end Alembic commands ###
