"""rename a column

Revision ID: 19e55b71890a
Revises: 34447ec2c674
Create Date: 2016-03-29 20:34:58.601453

"""

# revision identifiers, used by Alembic.
revision = '19e55b71890a'
down_revision = '34447ec2c674'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_day_price', 'adj_volume',
        new_column_name='adj_close')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_day_price', 'adj_close',
            new_column_name='adj_volume')
        ### end Alembic commands ###
