"""add about fund tables

Revision ID: 1a3c57290c1d
Revises: 18a31b795743
Create Date: 2016-04-08 22:15:25.663878

"""

# revision identifiers, used by Alembic.
revision = '1a3c57290c1d'
down_revision = '18a31b795743'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('fund_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('fund',
    sa.Column('fund_code', sa.String(length=12), nullable=False),
    sa.Column('fund_name', sa.String(length=32), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['fund_company.company_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['fund_type.type_id'], ),
    sa.PrimaryKeyConstraint('fund_code')
    )
    op.create_table('fund_stock_data',
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('fund_code', sa.String(length=12), nullable=True),
    sa.Column('stock_code', sa.String(length=12), nullable=True),
    sa.Column('public_date', sa.Date(), nullable=False),
    sa.Column('stock_amount', sa.Integer(), nullable=True),
    sa.Column('stock_value', sa.Float(), nullable=True),
    sa.Column('stock_value_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fund_code'], ['fund.fund_code'], ),
    sa.ForeignKeyConstraint(['stock_code'], ['stock_new.stock_code'], ),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('fund_code', 'stock_code', 'public_date')
    )
    op.create_table('fund_value',
    sa.Column('data_id', sa.BigInteger(), nullable=False),
    sa.Column('fund_code', sa.String(length=12), nullable=True),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('accumulative_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fund_code'], ['fund.fund_code'], ),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('fund_code', 'trading_date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund_value')
    op.drop_table('fund_stock_data')
    op.drop_table('fund')
    op.drop_table('fund_type')
    op.drop_table('fund_company')
    ### end Alembic commands ###
