"""added a column

Revision ID: 34447ec2c674
Revises: 4e935e68cc05
Create Date: 2016-03-29 20:30:07.868093

"""

# revision identifiers, used by Alembic.
revision = '34447ec2c674'
down_revision = '4e935e68cc05'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_day_price', sa.Column('close_price', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_day_price', 'close_price')
    ### end Alembic commands ###
