"""add day price table

Revision ID: 4e935e68cc05
Revises: b26d93aaef4
Create Date: 2016-03-29 17:05:14.658025

"""

# revision identifiers, used by Alembic.
revision = '4e935e68cc05'
down_revision = 'b26d93aaef4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_day_price',
    sa.Column('data_id', sa.BigInteger(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=True),
    sa.Column('stock_code', sa.String(length=12), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('adj_volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stock_new.stock_code'], ),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('stock_code', 'trading_date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_day_price')
    ### end Alembic commands ###
